apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  # local:
  # push: false
  googleCloudBuild:
    projectId: pacific-destiny-272718
  artifacts:
    - image: us.gcr.io/pacific-destiny-272718/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .